#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnova
Version  : 0.15.0
Release  : 2
URL      : https://sourceforge.net/projects/libnova/files/libnova/v%200.15.0/libnova-0.15.0.tar.gz
Source0  : https://sourceforge.net/projects/libnova/files/libnova/v%200.15.0/libnova-0.15.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: libnova-bin = %{version}-%{release}
Requires: libnova-lib = %{version}-%{release}
Requires: libnova-license = %{version}-%{release}

%description
Documentation
Doxygen (http://www.doxygen.org) is needed to build documentation.
It can be generated by doing a "make doc" in doc/.

%package bin
Summary: bin components for the libnova package.
Group: Binaries
Requires: libnova-license = %{version}-%{release}

%description bin
bin components for the libnova package.


%package dev
Summary: dev components for the libnova package.
Group: Development
Requires: libnova-lib = %{version}-%{release}
Requires: libnova-bin = %{version}-%{release}
Provides: libnova-devel = %{version}-%{release}

%description dev
dev components for the libnova package.


%package lib
Summary: lib components for the libnova package.
Group: Libraries
Requires: libnova-license = %{version}-%{release}

%description lib
lib components for the libnova package.


%package license
Summary: license components for the libnova package.
Group: Default

%description license
license components for the libnova package.


%prep
%setup -q -n libnova-0.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539760371
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1539760371
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libnova
cp COPYING %{buildroot}/usr/share/package-licenses/libnova/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libnovaconfig

%files dev
%defattr(-,root,root,-)
/usr/include/libnova/aberration.h
/usr/include/libnova/airmass.h
/usr/include/libnova/angular_separation.h
/usr/include/libnova/apparent_position.h
/usr/include/libnova/asteroid.h
/usr/include/libnova/comet.h
/usr/include/libnova/dynamical_time.h
/usr/include/libnova/earth.h
/usr/include/libnova/elliptic_motion.h
/usr/include/libnova/heliocentric_time.h
/usr/include/libnova/hyperbolic_motion.h
/usr/include/libnova/julian_day.h
/usr/include/libnova/jupiter.h
/usr/include/libnova/libnova.h
/usr/include/libnova/ln_types.h
/usr/include/libnova/lunar.h
/usr/include/libnova/mars.h
/usr/include/libnova/mercury.h
/usr/include/libnova/neptune.h
/usr/include/libnova/nutation.h
/usr/include/libnova/parabolic_motion.h
/usr/include/libnova/parallax.h
/usr/include/libnova/pluto.h
/usr/include/libnova/precession.h
/usr/include/libnova/proper_motion.h
/usr/include/libnova/refraction.h
/usr/include/libnova/rise_set.h
/usr/include/libnova/saturn.h
/usr/include/libnova/sidereal_time.h
/usr/include/libnova/solar.h
/usr/include/libnova/transform.h
/usr/include/libnova/uranus.h
/usr/include/libnova/utility.h
/usr/include/libnova/venus.h
/usr/include/libnova/vsop87.h
/usr/lib64/libnova.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnova-0.15.so.0
/usr/lib64/libnova-0.15.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnova/COPYING
